### PR TITLE
WL-3366

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Adding neo- prefix to skin

### CODE REVIEW

**Comment by buckett** [comment]
I know the login tool pulled in a dependency on portal-util to handle the calculating of the skin name using `org.sakaiproject.portal.util.CSSUtils#adjustCssSkinFolder(String)` is that not needed in rwiki?

**Comment by nicholaswilson100** [comment]
Thanks, much cleaner.

**Comment by buckett** [comment]
I've just seen some changes come through for wl-help and it looks like the better ways is to just pull out the request attribute "sakai.html.head" or actually maybe just sakai.html.head.css. You can see this in: `org.sakaiproject.portal.tool.ToolPortal#setupForward`. The reason it's better is that all the logic is in one place and you benefit from other changes, such as automatic invalidation.

**Comment by nicholaswilson100** [comment]
Unforutnately org.sakaiproject.portal.tool.ToolPortal#setupForward doesn't get hit when you go to Wiki -> Info > Public View so the request attribute "sakai.html.head" is null when you get to uk.ac.cam.caret.sakai.rwiki.component.service.impl.XSLTEntityHandler#outputContent.

**Comment by buckett** [comment]
Ah, cool.

**Pull request merged**
